### ISSUE TITLE
Pre-allocate port range for exclusive use by the Supervisor

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-supervisor#100]
User app containers and the Supervisor share the same network interfaces, so conflicts could arise. In the case of port 48484 (API) this is not a problem, because it is bound before the app containers are loaded. 

In the case of the webterminal, however, it is possible that a user application has already bound to the particular port before the service is started (this is why we had the workaround of incrementing the server's port number on each retry). Furthermore, we might need more ports in the future so preallocating a high port range might make sense.

**Comment by pcarranzav** [comment]
@lekkas I guess we can close this now the web terminal is external to the supervisor?

**Comment by lekkas** [comment]
Web terminal was one example that required preallocated ports, if we no longer need such a feature for the supervisor we can close the issue.
