### ISSUE TITLE
Reduce noise in logs

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-supervisor#101]
Reduce noise by not logging handled exceptions.

**Comment by pcarranzav** [comment]
:+1:
The main place where we log exceptions that are handled is in [dockerUtils.cleanupContainersAndImages](https://github.com/resin-io/resin-supervisor/blob/master/src/docker-utils.coffee#L195)

Think you can handle this one @lekkas ?

**Comment by lekkas** [comment]
Sure, thanks for the tip @pcarranzav ! I'm already working on a separate branch for this (see https://github.com/resin-io/resin-supervisor/commit/a9c5a1ac7cf2178047619557869939283da1e3ee) . It's still a WIP, I'll revisit it since I went berzerk with removing logs and should probably keep more that I initially thought :)

**Comment by pcarranzav** [comment]
Cool @lekkas - could  you rename the branch to start with the issue number so that waffle picks  it up as "In Progress"?
