### ISSUE TITLE
Adding deltas to a running supervisor

### ISSUE THREAD

**Issue by agherzan** [resin-io/resin-supervisor#103]
# Description 
A supervisor that is running without deltas starts using them.

# Steps to reproduce issue 
Use the board from TC09, without reprovisioning.
Add an *application-wide* RESIN_SUPERVISOR_DELTA = 1 env var. (It is important that the value is 1).
Push an update to the application (e.g. changing what is outputted to the console).

# Expected result 
When setting RESIN_SUPERVISOR_DELTA, the device  should *not* restart the app.
The device should download the update correctly after pushing.
Opening a web terminal and running "env" should show that the env var is correctly set (RESIN_SUPERVISOR_DELTA=1).

# Actual result 
Setting RESIN_SUPERVISOR_DELTA restarted the app on the device.

# Other information 
Reported by: Andrei Gherzan 

Test configuration: Zynq ZC702 

Test case number: TC10 

Test run: [https://resinio.testlodge.com/projects/16238/runs/196239?tab=2&run_section_id=176170&executed_case_id=9459483#executed_case_9459483](https://resinio.testlodge.com/projects/16238/runs/196239?tab=2&run_section_id=176170&executed_case_id=9459483#executed_case_9459483)

**Comment by floion** [comment]
Test case should probably be changed to read:

"Add an application-wide RESIN_SUPERVISOR_DELTA = 1 config var"

**Comment by pcarranzav** [comment]
I like your bug report style @agherzan
