### ISSUE TITLE
Env var to specify container restart policy

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#106]
Add a `RESIN_APP_RESTART_POLICY` env var that can take the values specified in: https://docs.docker.com/engine/reference/run/#restart-policies-restart
This should be passed to docker when running the container.

This will allow users to make their app auto-restart on exit.

**Comment by stdexcept** [comment]
Could we make the default to auto-restart?

**Comment by craig-mulligan** [comment]
@stdexcept If you set it as an application wide environment variable, all devices within that application will be set to auto-restart. Would that suffice?

**Comment by stdexcept** [comment]
That would suffice, as long as it's not required for every device individually.

**Comment by craig-mulligan** [comment]
@stdexcept Yip, you'd just need to set it once on an app level and the devices would automatically pick up the new config.

**Comment by stdexcept** [comment]
Hi, 

Can this be prioritised higher? It seems like a ten minute fix but the implications are quite big. We really needed this months ago.

**Comment by alexandrosm** [comment]
Hi @stdexcept, we don't believe this to be a 10-minute fix (otherwise we would have done it) but happy to take a PR.

**Comment by pcarranzav** [comment]
@stdexcept the reason this is not a ten minute fix is that it requires an upgrade to docker in the host OS that still hasn't made it to production. We're working on it.

**Comment by shaunmulligan** [comment]
@pcarranzav is this gonna be merged and tested now with the new docker version?
