### ISSUE TITLE
Raspberry Pi 3 config.txt is not updated

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-supervisor#109]
https://github.com/resin-io/resin-supervisor/blob/a2fa396b9fad8656d7c6c8e76d8a4b57b61a00e5/src/device.coffee#L75

**Comment by pcarranzav** [comment]
Will fix when implementing #107

**Comment by emirotin** [comment]
Yeah, I've added this one to keep track in the support convo

**Comment by pcarranzav** [comment]
The right thing to do indeed :) Cheers

**Comment by lorenzo-stoakes** [comment]
To give a bit more context - it's not updated when using a config var with the appropriate prefix is set.
