### ISSUE TITLE
Decide how to manage data migrations/deletions when changing app

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#110]

**Comment by lekkas** [comment]
As discussed in the arch call, we should remove app data by default when moving a device to a new application cc @pcarranzav @shaunmulligan

**Comment by shaunmulligan** [comment]
@pcarranzav this will be implemented in multicontainer right?

**Comment by alisondavis17** [comment]
@pcarranzav @shaunmulligan will this in fact be implemented in multicontainer?

**Comment by pcarranzav** [comment]
Yes, this was closed in #482 - all volumes are deleted when a device changes to a new app.
