### ISSUE TITLE
Device hostname not set in host OS

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/resin-supervisor#121]
Currently a device's `hostname` is set to  <device-type>-<device uuid> on devices, but only _within the container_, adjusting the container's `/etc/hostname` and this in no way percolates to a local DNS which picks up hostname on DHCP lease assignment. Instead, the host OS's hostname is used, which defaults to the device type, e.g. `raspberrypi2`.

In local networks which have their own DNS this can result in duplication (and hence, problems.)

We need to find a way to synchronise the two correctly.

One suggestion courtesy of @alexandrosm is the follows:
- at boot, the device determines its hostname.
  - first, it looks for a "hostname" value in the config.json file
  - if nothing, it looks for the uuid, and the hostname becomes `<device-slug>-<uuid last 7 digits>`
  - if there is no uuid, it sets the hostname to `<device-slug>-temp-<random 7 digits>`
- the host OS has a "change uuid" script/command that can be called by the supervisor
  - the OS changes the uuid value in the config.json file
  - if the there is no "hostname" value in the config.json file , the device restarts connman (or whatever connection manager) to change its hostname in the network.
- the host OS has a "change hostname" script/command that can be called by the supervisor.
  - the OS changes the hostname value in the config.json file
  - upon change of the hostname, the device restarts connman (or whatever connection manager) to change its hostname in the network.

This issue will likely touch the host OS and base images, we can create tickets there as necessary.

**Comment by ebuildy** [comment]
If it can help, here a command to run inside the container that will set the host hostname:

````
DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host_run/dbus/system_bus_socket dbus-send --system --print-reply --reply-timeout=2000 --type=method_call --dest=org.freedesktop.hostname1 /org/freedesktop/hostname1 org.freedesktop.hostname1.SetStaticHostname string:"HOSTNAME" boolean:true
````

I had to reboot the device after that, and I can see the hostname is set fine.

**Comment by pcarranzav** [comment]
This has been addressed in resinOS some time ago, as the hostname in the hostOS is now the first part of the uuid. Closing.

(and thanks for the workaround @ebuildy!)
