### ISSUE TITLE
Delta fetch resume support

### ISSUE THREAD

**Issue by Page-** [resin-io/resin-supervisor#140]
Adding the ability to resume a delta download at any point would improve things under poor network conditions massively.  Currently it is restarted from the beginning each time, and relies on the reduced size of most deltas to offset the lack of any resume support.

**Comment by surfacescan** [comment]
I agree - this is something I'm testing out now as most of our deployments *would be/ will be* in Africa on limited connectivity - often a 3g modem will be the connection.  So a resume download would be a HUGE bonus

**Comment by gkapkowski** [comment]
Guys any progress on this issue? I can see that PR is in-review for quite a while now.

**Comment by pcarranzav** [comment]
It's been delayed since that PR didn't work as expected. We'll be working on it again soon.

**Comment by pcarranzav** [comment]
This was fixed by #483 and subsequent fixes
