### ISSUE TITLE
Expose api token as RESIN_API_KEY to the containers

### ISSUE THREAD

**Issue by jviotti** [resin-io/resin-supervisor#18]
This variable is used to authenticate on the JavaScript/Python SDKs. Since the supervisor already uses the api key to communicate with the Resin.io infrastructure, we can expose it so users can use the SDK and dependants easier.

**Comment by pcarranzav** [comment]
@jviotti shouldn't this be `RESIN_API_KEY`? We have an API key and not a token in the supervisor.

**Comment by jviotti** [comment]
@pcarranzav Yeah, sorry my mistake, it's `RESIN_API_KEY`.

**Comment by nghiant2710** [comment]
@pcarranzav Will we have this soon?
