### ISSUE TITLE
Ensure we don't kill a locked user's app if the supervisor crashes and restarts

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#20]
Every time the supervisor starts, it clears all locks by doing unlockAndStart(app).
However, it should check whether the app container is already running and should have _some_ way to identify if the lock belongs to the app (and not to a previously crashed supervisor) - in this case, it should **not** unlock since it means the app is actually locked and in a critical section.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_vqp)

**Comment by lekkas** [comment]
Connects to https://github.com/resin-io/hq/pull/488/files
