### ISSUE TITLE
Add timestamp to supervisor logs

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#206]

**Comment by samirop** [comment]
Hello! Did this succeed? And in that case, how do you add timestamps to supervisor logs?  Thanks in advance

**Comment by pcarranzav** [comment]
Hi @samirop - there is PR linked above (#207) that adds the timestamps. Supervisor logs are generally only relevant for resin-supervisor development/debugging - is there anything specific you're looking for?

**Comment by samirop** [comment]
Hi @pcarranzav, Thanks for your fast reply! I've just realized that this is a resin-supervisor, I was looking to add timestamps to the supervisord logs, my mistake :(  (unless your solution is related)

**Comment by pcarranzav** [comment]
No worries @samirop! I think the repo you're looking for is this: https://github.com/Supervisor/supervisor
Good luck!

**Comment by samirop** [comment]
Yes it is, thanks a lot!
