### ISSUE TITLE
Supervisor API endpoint for resource monitoring

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#21]
Report RAM/CPU/network/disk usage

**Comment by pcarranzav** [comment]
Still working on this @lifeeth ?

**Comment by lifeeth** [comment]
@pcarranzav Nope

**Comment by pcarranzav** [comment]
@shaunmulligan I don't suppose we still want this as part of the supervisor API? Should I close this pending further architecture discussions? We have https://github.com/resin-io/hq/issues/77 to track the feature in a more global way.

(Closing but feel free to reopen)
