### ISSUE TITLE
host OS kmod linker is at a different path on amd64 platforms

### ISSUE THREAD

**Issue by petrosagg** [resin-io/resin-supervisor#221]
Yocto puts the linker at `/lib/ld-linux-x86-64.so.2`, but debian puts it at `/lib64/ld-linux-x86-64.so.2`. Since we bind-mount the `kmod` binary from the host in the container, it fails to run on amd64 platforms.

The current workaround is to run `ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2` in the container.

The supervisor could bind-mount the linker as well so that the workaround isn't needed

**Comment by pcarranzav** [comment]
Will be fixed in base images
(Unless @petrosagg says otherwise)
