### ISSUE TITLE
Current OOM killer protection does not protect the supervisor

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/resin-supervisor#225]
The current adjustment to the OOM killer scoring fails to protect the supervisor as it only adjusts the score (via `oom_score_adj`) for the first process in the supervisor cgroup which happens to be a supervisord process, not the actual node or go supervisors.

This protection needs to be updated to adjust the score for these processes.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lfo)

**Comment by pcarranzav** [comment]
Closed by #482 since we removed the faulty OOM protection from the gosuper code.
I suppose if we want to protect the supervisor from OOM we can use docker's oom-score-adj option when starting it? @agherzan @petrosagg
