### ISSUE TITLE
Custom user-agent on supervisor

### ISSUE THREAD

**Issue by abresas** [resin-io/resin-supervisor#230]

**Comment by pcarranzav** [comment]
Quote from @Page- :
>it was removed for bandwidth reasons btw
>but supervisor is pretty unique in that it's about the only thing that talks to the api with no user-agent, ie it's custom user-agent is to not have one

So closing this for now, as the bandwidth reason is quite important (even if the BW difference is small), and the no-user-agent distinction seems to be enough for now.

**Comment by dfunckt** [comment]
The Supervisor should be sending a User-Agent header that identifies at least itself (but also the host OS it's running on, if possible) as we recently felt the pains of not being able to identify which specific Supervisor the backend communicates with.

(It'd be awesome to have it with all ResinOS 2.0 devices.)

**Comment by pcarranzav** [comment]
Header format would be `Supervisor/X.Y.Z (Linux; Resin OS v.2.A.B.revC; Dev)`
