### ISSUE TITLE
Add option to specify stop signal for user application container

### ISSUE THREAD

**Issue by nghiant2710** [resin-io/resin-supervisor#233]
Connects to https://github.com/resin-io-library/base-images/pull/77#issuecomment-240066976.

We should have a resin environment variable (like RESIN_CONTAINER_STOP_SIGNAL) with `SIGRTMIN+3` as the default value. So that systemd in the container will be stopped gracefully when container stopped.

**Comment by shaunmulligan** [comment]
+1

**Comment by petrosagg** [comment]
This is not an issue of the supervisor, we can handle it in the base images. Closing
