### ISSUE TITLE
Host Config Var to set custom Hostname

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-supervisor#241]
We should allow a `RESIN_HOST_HOSTNAME` env var which would set the hostname of the device. This is useful to some users when they have multiple devices on the same network and they all show up with the same name.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_l3e)

**Comment by pcarranzav** [comment]
Closing this since #547 added a supervisor API endpoint to achieve this. Please let me know if this is not sufficient for the desired use case.
