### ISSUE TITLE
We should have metalogs indicating Shutting down, Rebooting or Purging data

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-supervisor#242]
We should indicate on the logs that the device got the reboot or shutdown command and will be attempting to shutdown. In general its hard for a user to know if their action has gone through or not, so can result in them sitting and staring at the device for a minute or 2 waiting for something to happen.

**Comment by alexandrosm** [comment]
I wonder if we should replace the metalogs alltogether with the action logs
eventually.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by pcarranzav** [comment]
Edited title to include also Purge.
