### ISSUE TITLE
Expose a few extra useful RESIN_ Env Vars to the container

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#25]
expose the following Env Vars on the device:
RESIN_APP_NAME
RESIN_DEVICE_NAME_AT_INIT
RESIN_DEVICE_TYPE
RESIN_DEVICE_ID (??)

**Comment by pcarranzav** [comment]
Also RESIN_HOST_OS_VERSION

**Comment by lorenzo-stoakes** [comment]
__EDIT:__ Suffix `RESIN_DEVICE_NAME` with `_AT_INIT` to make it clear to the user that the device name may have changed since the container started running. The alternative is to restart the device container on any device name change, but this is brutal and unexpected behaviour so not a good solution.

**Comment by pcarranzav** [comment]
Also RESIN_APP_ID as per #124

**Comment by shaunmulligan** [comment]
Could we also add the git commit hash? Could name it `RESIN_RELEASE_ID` so that it is generic enough, so that if the builder later has different non-git backends, it will still be consistent.

**Comment by pcarranzav** [comment]
Yeah, we could. BTW @shaunmulligan - commit is also available on the [GET /v1/device](https://github.com/resin-io/resin-supervisor/blob/master/docs/API.md#get-v1device) and [GET /v1/apps/{appId}](https://github.com/resin-io/resin-supervisor/blob/master/docs/API.md#get-v1appsappid) endpoints, in case anyone needs it now.

**Comment by shaunmulligan** [comment]
Also would be nice to have hardware MAC address

**Comment by pcarranzav** [comment]
I'm implementing some of these in #238.
Instead of RESIN_RELEASE_ID I used RESIN_APP_RELEASE to expose the commit.
@shaunmulligan please check https://github.com/resin-io/resin-supervisor/pull/238/files#diff-e7632c024955e4a1dc429d3253cbe6bcR162 and let me know if you approve.

I'll create separate issues for device ID and MAC address.

**Comment by shaunmulligan** [comment]
@pcarranzav I approve 👍
