### ISSUE TITLE
dind: bind-mount /bin/kmod from the host to the resin-supervisor-dind host

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-supervisor#258]
Ref: https://github.com/resin-io-modules/docker-toolbelt/pull/1#issuecomment-246105218

**Comment by lekkas** [comment]
Moved this issue manually to Testing, lmk if it should normally be done automatically

**Comment by pcarranzav** [comment]
@lekkas the process for that is still manual - just a note: once the PR is merged it goes to Waiting for staging, and to Testing only once it's been deployed to staging with the bump in meta-resin.

**Comment by pcarranzav** [comment]
However, in this case we can just close the issue as it only affects the dind version and not production builds.
