### ISSUE TITLE
Add a delete-then-download update strategy

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#260]
Useful for extreme low-space scenarios.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_nif)

**Comment by BrianAdams** [comment]
If I have an existing download in progress via a different strategy, will the system recognize the change in deployment strategy and switch to this strategy mid download?  I would prefer to us the existing strategies by default, but by the time I find out I am out of space I am already in the middle of an update. It would be good to be able to change to the new strategy mid download to to force completion of the application download.

**Comment by Page-** [comment]
Changing the strategy mid-download will be picked up on the next update attempt (eg when it fails and retries), which should cover the case of trying another strategy and then finding out that the delete-then-download strategy is required
