### ISSUE TITLE
Seeing Double "Starting" and "Started" app logs

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-supervisor#269]
In the screenshot you can see that once my application container has started, the supervisor seems to randomly print another 2 meta-logs, and then nothing else. It doesnt seem to actually start the container twice, but rather just prints those logs again.
<img width="918" alt="screen shot 2016-09-24 at 19 07 48" src="https://cloud.githubusercontent.com/assets/3915043/18869379/06c4b4a6-84a4-11e6-88c2-4b32831b7ed0.png">

**Comment by Page-** [comment]
@curcuz do you also have this with the devices that have multiple containers?

**Comment by pcarranzav** [comment]
This would be the expected behavior if the supervisor restarted itself for some reason, or the device rebooted. Closing until someone reproduces and we can get proper logs to debug.
