### ISSUE TITLE
Improve web terminal (security, UX) using one of many alternatives.

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#27]
Consider:
- docker exec instead of nsenter
- ssh
- gotty

**Comment by pcarranzav** [comment]
Another note from the past: "When an application is updated any open terminal session tunnels are terminated - can we automatically reopen a new session on the updated container (although the open terminals would be lost, new ones should be able to be opened)" ?

**Comment by shaunmulligan** [comment]
Could we also use the same mechanism to allow local IP SSH to their container, so they wouldn't have to install SSH. Lots of people would prefer this over webterminal

**Comment by pcarranzav** [comment]
The web terminal functionality has been refactored and moved outside the supervisor, so this is no longer relevant to this repository.
