### ISSUE TITLE
Expose MAC address as an env var?

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#277]
In #25, @shaunmulligan proposed exposing MAC address as an environment variable.

I'm not sure if it's a good idea, given that the interface from which to get the MAC address will vary form board to board, and it can easily be obtained by other means (e.g. `ifconfig -a`).
But I'm opening this to allow discussion.

**Comment by alexandrosm** [comment]
what's the benefit of having an env var? i think what shaun wanted was to
see it in the dashboard though, not as an env var. maybe I'm misremembering?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by pcarranzav** [comment]
I don't really see the benefit, but that's what Shaun said in the linked issue.

**Comment by shaunmulligan** [comment]
@pcarranzav yeah @alexandrosm is correct, quiet a few users have asked that MAC address be surfaced on the Dashboard. One user even asked if we could enable a way they could send a value, or some kinda data/status/identifier to the dashboard, but thats a different issue :)

**Comment by pcarranzav** [comment]
Okay, makes sense. I'll close this one and open a new one about reporting MAC address to the API.
