### ISSUE TITLE
Possible typo in /run/dbus:/host_run/dbus bind mount

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-supervisor#312]
In: https://github.com/resin-io/resin-supervisor/blob/master/src/utils.coffee#L258

```coffeescript
'/lib/modules:/lib/modules'
'/lib/firmware:/lib/firmware'
'/run/dbus:/host_run/dbus'
'/run/dbus:/host/run/dbus'
'/var/lib/connman:/host/var/lib/connman'
```

Is the `'/run/dbus:/host_run/dbus'` bind mount needed?

**Comment by pcarranzav** [comment]
Yes, for backwards compatibility. We advertised host_run before we settled for host/run.
