### ISSUE TITLE
Moving applications while the update lock is set causes the old app not to be stopped

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#348]
When a user executes a device move, the supervisor sees a state change in the API that tells it to start running the new app, and remove the old one. This will cause the supervisor to try to start the new app and remove the old one in parallell (as it is done within a [promise .map](https://github.com/resin-io/resin-supervisor/blob/master/src/application.coffee#L639)).

If the update lock on the old app is set, stopping it will fail, but starting the new one will succeed, so the old app will remain running alongside the new (aka "duplicated containers").

In older devices this will also trigger the bug fixed in #346 - so the error will not be sent to the device logs.

A workaround to avoid this issue is to set the lock override (`RESIN_SUPERVISOR_OVERRIDE_LOCK = 1`, i.e. setting the lock override in the device's Actions page) *before* moving to the new app, which will cause the app to be properly stopped while the new one is being started.

If a device falls into this state, a hotfix can be applied by hitting the Supervisor API's `/v1/update` endpoint with the force parameter, e.g. running this from the webterminal:

```
curl -X POST --data '{"force":true}' -H 'Content-Type: application/json' $RESIN_SUPERVISOR_ADDRESS/v1/update?apikey=$RESIN_SUPERVISOR_API_KEY
```

This will cause the supervisor to run an update cycle forcing all locks, which will allow it to stop the old app.

The proper fix will require a re-architecture of how app moves are handled, somehow allowing the transition to be more orderly executed, ideally also applying update strategies for the change. This might be a bit of a challenge as it involves changes to the core update cycle, and we need to consider how it may affect future multi-container implementations.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1wo1)

**Comment by emirotin** [comment]
Happened again here: https://app.frontapp.com/open/cnv_5uu3k1
