### ISSUE TITLE
Make supervisor logs on the run-supervisor target available without entering the container

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#35]
We want to run the e2e tests using the emulated supervisor in the resin-supervisor repository.

The logs currently sit inside the resin_supervisor_1 container created by resin-supervisor and it is hard to stream them from the outside. Another problem is that the file is not created immediately, and the tests would have to wait for the file to appear first to read it.

Ideally the logs would be available on the output of the container, available through `docker logs`

**Comment by pcarranzav** [comment]
@lifeeth still working on this?

**Comment by lifeeth** [comment]
@pcarranzav Nope - unassigning myself.

**Comment by pcarranzav** [comment]
The supervisor now logs directly to docker, so this can be closed now.
