### ISSUE TITLE
The lock on the new app is already there when it's moved, but the override is not set on the new app

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-supervisor#358]
This is another edge case associated with users using lock files and moving devices between app.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_wn9)

**Comment by Page-** [comment]
This is probably due to manual intervention on behalf of people suffering from #348 where the lockfile of the old app was not cleaned up, so when moving back to that app the lockfile is still there
