### ISSUE TITLE
Ensure the OOM killer doesn't kill critical supervisor processes

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#39]
Using /proc/<pid>/oom_adj ?

**Comment by lifeeth** [comment]
I was trying out https://github.com/shirou/gopsutil and was planning on using it to provide more metrics as well. Also we can set the max memory that can be used by a container and retain some for the supervisor - Mumble later today?

**Comment by lifeeth** [comment]
https://github.com/resin-io/resin-supervisor/issues/21 Becomes a subpart of this.
