### ISSUE TITLE
Local mode doesn't persist over reboots. 

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-supervisor#408]
The supervisor claims to be in local mode after reboot but is actually still cleaning up old containers. 

Steps to reproduce: 
- put the device in local mode
- ssh into host
- docker pull an image 
- docker ps -> will list the newly returned image. 
- reboot the device
- docker ps -> image will be gone (cleaned up by the supervisor)
- any new image you pull will be deleted.

**Comment by pcarranzav** [comment]
After some investigation it turned out this is not the case, it was just that local mode wasn't being set because the app had no commits (which is currently necessary for the supervisor to get *any* config variables)

**Comment by alexandrosm** [comment]
@pcarranzav that sounds like another bug we should fix, no?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by craig-mulligan** [comment]
@pcarranzav, in my view it is a 'bug' too, I assume the change isn't so simple because of the way things currently work.. Will this go into the super rewrite or is there a way to do it sooner? It seems very unnatural to force certain conditions of local mode users.
