### ISSUE TITLE
Remove requirement of `\n` characters in config.json

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-supervisor#41]
Currently the config.json has these ugly `\n` newline chars that are painful for the users to work with when changing network settings:
here is an example:
```
"files": {
    "network/settings": "[global]\nOfflineMode=false\n\n[WiFi]\nEnable=true\nTethering=false\n\n[Wired]\nEnable=true\nTethering=false\n\n[Bluetooth]\nEnable=true\nTethering=false",
    "network/network.config": "[service_home_ethernet]\nType = ethernet\nNameservers = 8.8.8.8,8.8.4.4\n\n[service_home_wifi]\nType = wifi\nName = My_Wifi_Ssid\nPassphrase = my super secret wifi passphrase\nNameservers = 8.8.8.8,8.8.4.4"
  }
```

**Comment by pcarranzav** [comment]
These are not used by the supervisor but by resin-io/meta-resin - and they are Connman configuration files. Don't know how this could be fixed, but in any case I think this is an issue for meta-resin.

**Comment by shaunmulligan** [comment]
fair enough, i will raise on meta-resin
