### ISSUE TITLE
Image cleanup doesn't happen while update lock is set, potentially causing out of space

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#410]
When the update lock is set, update cycles never finish, so the docker image cleanup doesn't happen.
This causes the device to potentially run out of space if the user pushes several new versions sequentially: the supervisor downloads the newer version (as expected), but doesn't cleanup the old one that will never be used.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1d2t)

**Comment by alexandrosm** [comment]
Clearly we need to not remove images in use. Images not in use should be
fair game. Another API for ect?

**Comment by pcarranzav** [comment]
That's the plan @alexandrosm, WIP in #411
