### ISSUE TITLE
Differentiate between different logging channels (stderr/stdout etc)

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io/resin-supervisor#416]
We'd like to differentiate between different log outputs on the dashboard.
See https://github.com/resin-io/resin-ui/issues/75 for more information.

**Comment by pcarranzav** [comment]
This was actually closed in #482 and #545 as we added an `isStderr` flag to logs (abbreviated to `e` in pubnub logs). @LucianBuzzo I guess this can now be addressed on the UI side?
