### ISSUE TITLE
Remove deprecated wifiSsid and wifiKey fromconfig.json

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-supervisor#42]
AFAIK, wifiSsid and wifiKey are no longer used by any parts of the system, and now they just serve as a point of confusion.

**Comment by pcarranzav** [comment]
I don't see them anywhere in this repo. The config.json generation is handled by https://github.com/resin-io/resin-device-config - is it still producing these fields?

**Comment by shaunmulligan** [comment]
Yeah its still being produced, also I'm not sure the image maker is using that module yet

**Comment by pcarranzav** [comment]
This is for image-maker then.
