### ISSUE TITLE
Compiling according to README fails with missing manifest

### ISSUE THREAD

**Issue by imrehg** [resin-io/resin-supervisor#422]
When following the steps to compile as described in the [README](https://github.com/resin-io/resin-supervisor#deploy-your-local-version-to-a-docker-registry), the compilation fails.

I'm running it as `make ARCH=amd64 SUPERVISOR_IMAGE=imrehg/resin-supervisor:master deploy`, and the result (just showing the section that errors out):

```
...
docker run --rm \
	-v `pwd`/build/amd64:/build \
	resin/go-supervisor-amd64:master
sed 's/%%ARCH%%/amd64/g' Dockerfile.runtime.template | sed 's/%%BASE_IMAGE_TAG%%/resin\/amd64-supervisor-base:master/g' > Dockerfile.runtime.amd64
echo "ENV VERSION=4.1.2 \\" >> Dockerfile.runtime.amd64
echo "    DEFAULT_PUBNUB_PUBLISH_KEY=pub-c-bananas \\" >> Dockerfile.runtime.amd64
echo "    DEFAULT_PUBNUB_SUBSCRIBE_KEY=sub-c-bananas \\" >> Dockerfile.runtime.amd64
echo "    DEFAULT_MIXPANEL_TOKEN=bananasbananas" >> Dockerfile.runtime.amd64
docker build \
	 \
	 \
	 \
	-f Dockerfile.runtime.amd64 \
	--pull \
	-t "resin/amd64-supervisor:master" .
Sending build context to Docker daemon  43.03MB
Step 1/10 : FROM resin/amd64-supervisor-base:master
manifest for resin/amd64-supervisor-base:master not found
make: *** [Makefile:153: supervisor] Error 1
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1ier)

**Comment by pcarranzav** [comment]
Yeah, this is related to #399 (but it's true that it needs a separate issue)
