### ISSUE TITLE
Multiple entries of the same dtparam in config.txt

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-supervisor#423]
Adding the `RESIN_HOST_CONFIG_dtparam = audio=off` results in multiple entries in the config.txt on 
**HOST OS VERSION**
Resin OS 2.0.0+rev3 (dev)
**SUPERVISOR VERSION**
4.1.1 
```
root@62bf4c3:/mnt/boot# cat config.txt | grep audio
## hdmi_ignore_edid_audio
##     Pretends all audio formats are unsupported by display. This means ALSA
##     1        Pretend all audio formats are unsupported
#hdmi_ignore_edid_audio=1
## hdmi_force_edid_audio
##     Pretends all audio formats are supported by display, allowing
##     1        Pretend all audio formats are supported
#hdmi_force_edid_audio=1
##     Don't dedicate a pll to PWM audio. This will reduce analogue audio
## audio
##     Enable the onboard ALSA audio
#dtparam=audio=off
dtparam=audio=off
dtparam=audio=off
dtparam=audio=off
```

I think in some cases this cause problems if trying to set back to `audio=on` because the very last entry will override all the others.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1ya1)

**Comment by shaunmulligan** [comment]
@pcarranzav this is actually more severe then I thought, it turns out that all `dtparams` are getting replaced by the one, see this example below:
**original config.txt on a newly downloaded image**
```
#dtparam=pwr_led_gpio=35
# Enable UART
enable_uart=1
dtparam=i2c_arm=on
dtparam=spi=on
disable_splash=1
avoid_warnings=1
dtparam=audio=on
```

**config.txt after `dtparam=audio=off` is applied from dashboard:
```
#dtparam=pwr_led_gpio=35
# Enable UART
enable_uart=1
dtparam=audio=off
dtparam=audio=off
disable_splash=1
avoid_warnings=1
dtparam=audio=off
```

You can see that both of the following were incorrectly replaced with `audio=off`:
```
dtparam=i2c_arm=on
dtparam=spi=on
```

This is obviously pretty problematic :/

**Comment by imrehg** [comment]
Run into it in the forums https://forums.resin.io/t/rpi3-clock-stretching-using-fleet-variables/1964

**Comment by imrehg** [comment]
Could also combine some of the lines into a single dtparam line, so that the supervisor just changes one line - documenting the default values, and telling people that they need to add those if they want to have the default behaviour?

See section 3.2 of https://www.raspberrypi.org/documentation/configuration/device-tree.md

Just ideation for possible workarounds / temporary fixes?

**Comment by imrehg** [comment]
This is still causing issues, and expect the issue to worsen until fixed.. :/ Linking another front issue where it was relevant.
