### ISSUE TITLE
Set the hostname on devices to match their name

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#46]
It would be very useful if devices had a hostname which matched the name they have on the dashboard, so you can tell at a glance what device you're working with, and see the device name appearing on your network
Should get set on provision, and update whenever the name changes

**Comment by shaunmulligan** [comment]
Would this cause issues for some users who rely on specific hostname, or set it themselves?

**Comment by pcarranzav** [comment]
If we do it before starting the user container, it shouldn't cause issues. Unless the supervisor starts when the user app is running... (e.g after a supervisor  update).
So dunno, needs discussion I guess (I ported the issue from JIRA).
Maybe @Page- @petrosagg @lifeeth have an opinion?

**Comment by pcarranzav** [comment]
See #121
