### ISSUE TITLE
Application logs date issue: application started before ntp synchronization.

### ISSUE THREAD

**Issue by zvin** [resin-io/resin-supervisor#488]
This leads to logs in the dashboard having the wrong date (the date of the last reboot).

Please see the logs attached in the front conversation.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_28jz)

Interesting parts of logs:

 - the device booted with this date "Jun 15 19:45:53"
 - systemd-tyimesyncd changed the date: `Jun 15 19:45:54 raspberrypi3 systemd-timesyncd[540]: System clock time unset or jumped backwards, restoring from recorded timestamp: Mon 2017-08-21 03:01:07 UTC`
 - the app started, logging some info with the wrong date
 - systemd-timesyncd changed the date again using an ntp server: `Aug 23 07:01:47 2aeea0b systemd-timesyncd[540]: Synchronized to time server 83.145.237.222:123 (0.resinio.pool.ntp.org).`

**Comment by pcarranzav** [comment]
Not sure if there's anything we can do here @zvin - logs will come with the date that the device has, whatever it is. Unless we make the docker service depend on ntp in Resin OS @agherzan @floion, does this sound reasonable?

**Comment by pcarranzav** [comment]
Closing this since it's not really a supervisor issue - the supervisor just uses whatever time the system has - and the new logger in the resin API could solve this on the API side.
