### ISSUE TITLE
Implement several update strategies

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#54]
kill-before-download
download-before-kill
hand-over

**Comment by lifeeth** [comment]
Checked by changing the ENV variable names from RESIN_SUPERVISOR_UPDATE_STRATEGY to _ RESIN_SUPERVISOR_UPDATE_STRATEGY 

1. Kill-then-download behaviour is not being honoured.

2. Additionally: Changing the ENV variables are triggering a container restart - these should be in the list of ENV variables that do no cause a container reboot.

**Comment by pcarranzav** [comment]
The variable is definitely on the special list; are you 100% sure you changed the env var name in *all* places?

**Comment by lifeeth** [comment]
@pcarranzav I ran a sed for all the *.js and *.coffee and then restarted the app with supervisorctl

**Comment by pcarranzav** [comment]
@lifeeth can you post the logs (internal and dashboard) please?

**Comment by pcarranzav** [comment]
(Otherwise I'll try to reproduce on Thursday)

**Comment by pcarranzav** [comment]
Tested and could not reproduce, it works fine. Discussed with @lifeeth that it was probably a problem with his test setup.
