### ISSUE TITLE
Prevent Update with Device / Environmental Variable

### ISSUE THREAD

**Issue by splitice** [resin-io/resin-supervisor#540]
There are many use cases (e.g debugging a device, different development teams etc) where devices may need to be prevented from updating.

It should be possible with an environmental variable to prevent updates from occuring.

**Comment by pcarranzav** [comment]
@splitice there are a few mechanisms already in place to achieve that:
* The update lock can prevent the supervisor from updating (intended to be used in critical sections of code, but could be used for debugging): https://docs.resin.io/runtime/update-locking/#update-locking
* Setting a device to a specific build https://docs.resin.io/tools/python-sdk/#function-set_to_build-uuid-build- - this is the recommended  way to make the device stick to a specific release, so even if you push new commits the device still stays in the specified version
* Using different applications for different development teams

That being said, would using an environment variable have a benefit above these for your particular use case?

**Comment by splitice** [comment]
Method 1. causes an issue when the device is rebooted, the app can then be updated.
Method 2. looks interesting, how does that behave when there is a new build pushed? Does it disable updates entirely once set? If so how do you return a device to the normal upgrade path?
Method 3. would require a large number  of applications which while not impossible to do would not be an ideal solution.

Personally I feel a device configuration variable would be a simple solution here.

**Comment by thgreasi** [comment]
WRT method 2, there is also the [staged-releases](https://github.com/resin-io-playground/staged-releases) playground repo.

**Comment by pcarranzav** [comment]
@splitice have you checked the staged-releases repo linked above? Hopefully that solves this for you.  If you set a device to a release, it will not update when a new build is pushed. You can then "unpin" the device with the same `set-device-to-a-build.sh` script by not specifying a commit.

**Comment by splitice** [comment]
@pcarranzav 

We have tried those scripts multiple times. Unfortunately the resin device never updates even when manually moving the device with ```set-device-to-a-build.sh```. The only way we have managed to get updates to work is via allowing fleet updates.

If I do an API select on the device I can see the build id is set, yet the commit remains the same and the device never updates.

**Comment by pcarranzav** [comment]
@splitice could you elaborate a bit more on how exactly you're calling the scripts? We have several users using them so there must be something about your particular use case that isn't working.

(I'll close this issue cause those scripts should address it, but we can keep discussing your problem with the scripts here)
