### ISSUE TITLE
Update locking documentation does not explicitly state that lockfile does not prevent update download

### ISSUE THREAD

**Issue by hedss** [resin-io/resin-supervisor#656]
Whilst the documentation suggests this, it is not explicit and probably should be.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_bln7)

**Comment by CameronDiver** [comment]
@hedss should this be in the docs repo instead?

**Comment by hedss** [comment]
@CameronDiver I've added this issue here because this document was referenced: https://github.com/resin-io/resin-supervisor/blob/master/docs/update-locking.md

We should probably either be pulling this into the main docs, or ensuring that the main docs build the relevant docs for the Supervisor from this.

**Comment by CameronDiver** [comment]
Oh I see, yeah that makes sense. @shaunmulligan @zwalchuk do you guys have a master plan for the supervisor documentation?

**Comment by CameronDiver** [comment]
Gotcha, I'll keep these updated then, thanks Zach.
