### ISSUE TITLE
Supervisor is not picking up the new device name on service restart

### ISSUE THREAD

**Issue by nazrhom** [resin-io/resin-supervisor#659]
In general every action that re-creates the application container should trigger an update of `RESIN_DEVICE_NAME_AT_INIT` and possibly other relevant env vars. 
 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_bn4r)

**Comment by CameronDiver** [comment]
@nazrhom could you link this with the support ticket please?
