### ISSUE TITLE
Support extlinux configuration for the jetson-TX family devices

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-supervisor#671]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_c1dn)

**Comment by imrehg** [comment]
@CameronDiver also for the TX1?

**Comment by CameronDiver** [comment]
Good catch :) changed.
