### ISSUE TITLE
Update attempts can hang after a failure

### ISSUE THREAD

**Issue by Page-** [resin-io/resin-supervisor#69]
The last thing logged in relation to updating is:
`Scheduling another update attempt due to failure:  2000 [...]`
with the only potential exception being `Event: Update notification {}`, with no attempt to actually perform the update

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_rau)

**Comment by lifeeth** [comment]
Could relate to https://github.com/resin-io/resin-supervisor/issues/19
