### ISSUE TITLE
When building a node.js docker image, don't install dev dependnecies

### ISSUE THREAD

**Issue by scriby** [resin-io/resin-supervisor#73]
Sorry, I'm sure this isn't the right place to report this issue, but I can't figure out where the right place would be.

I was just noticing that node.js projects are including the devDependencies in the Docker image builds. It would be faster and produce smaller images to not include them (`npm install --production`).

**Comment by emirotin** [comment]
Ping @nghiant2710, is it out `-onbuild` base image related?

**Comment by Page-** [comment]
It's from https://github.com/resin-io-library/base-images/blob/master/node/Dockerfile.onbuild.tpl - I've referenced it in resin-io-library/base-images#65

**Comment by pcarranzav** [comment]
Closing since it is now an issue for resin-io-library/base-images.
Thanks for reporting @scriby !
