### ISSUE TITLE
Docker healthchecks not working for v7.19.7 in legacy/classic/essentials

### ISSUE THREAD

**Issue by mikesimos** [resin-io/resin-supervisor#756]
May be related with recent changes [here](https://github.com/resin-io/resin-supervisor/blob/5a8191cf791e3d9d91eaa3c850dfd61408ddfb15/src/compose/utils.ts#L221).
(getHealthcheck uses _.defaults between the compose and image healthchecks, but the compose one will always have at least test: [ 'NONE' ], so this will always override the image's test).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_eccr)

**Comment by pcarranzav** [comment]
fixed in #759
