### ISSUE TITLE
Set download_progress to 0 when starting the download

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#77]
The UI expects this.

**Comment by dfunckt** [comment]
#78 is only half the story -- the supervisor must similarly reset both ``status`` and ``download_progress`` on finish to null :)

**Comment by pcarranzav** [comment]
It already does... download_progress is set to null at the end of this function, and status is changed immediately in the next step of the update

**Comment by dfunckt** [comment]
Which can happen after some delay, right? Thing is, what's defined as "Downloading" state is related to both ``status`` and ``download_progress``, like this:

```javascript
return State.UPDATING if device.download_progress? and device.status is 'Downloading'
```

So, if ``status`` is "Downloading" and progress null the inferred state is *not* "Updating", but rather undefined/idle -- and the UI ends displaying "Downloading" with no progress. Makes sense?

**Comment by dfunckt** [comment]
Actually, an argument for this is that it makes sense to reset the reported status to Idle anyway, since the device exited this state. The next request may never come through to the API and the device will end up appearing like it's in an inconsistent state.
