### ISSUE TITLE
Add additional online state when VPN is broken

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/resin-supervisor#79]
When there are issues with the VPN connection we show the device as offline. However on some occasions the device still has internet connectivity (typically because of network conditions resulting in the vpn domain not resolving correctly), yet there is no difference between this case and the device actually being offline.

The proposal is to add an additional state 'online (degraded connectivity)' or something similar to this to indicate that this is the case, and disable any VPN-required functionality.

This patch would need to span the UI as well at the very least and probably the API too, however it all begins in the supervisor :)

**Comment by pcarranzav** [comment]
Closing this as it is going to be handled in other parts of the resin infrastructure.
Any supervisor changes needed by that will cause specific issues to be created for that.
cc @shaunmulligan 

See https://github.com/resin-io/hq/issues/348
