### ISSUE TITLE
Document all the special env vars

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#87]
In the docs folder, and the resin docs.

**Comment by pcarranzav** [comment]
Also, add a docs section in the README pointing to the docs folder.

**Comment by pcarranzav** [comment]
@lifeeth I'll need your help here for the bandwidth control part :)

**Comment by lorenzo-stoakes** [comment]
Also add note about which env vars reboot the device/not, e.g. `HOST_CONFIG` and `LOG_TO_DISPLAY` are currently the only ones

**Comment by pcarranzav** [comment]
Closed in the main resin docs, see https://github.com/resin-io/docs/issues/201
